### ISSUE TITLE
Laravel Mix 6 + Vue 3 Support

### ISSUE THREAD

**Issue by mrmonat** [danielstgt/laravel-mix-svg-vue#4]
Hello,

do you plan to support Laravel Mix 6 (with Webpack 5) and Vue 3 in the near future?

**Comment by danielstgt** [comment]
Absolutely, as soon as Laravel Mix 6 leaves the beta phase and Vue 3 gets merged from the `vue-next` repository. Although Vue 3 support might be coming earlier.

**Comment by dacoto** [comment]
https://github.com/JeffreyWay/laravel-mix/releases/tag/v6.0.0

**Comment by danielstgt** [comment]
Laravel Mix v6 is supported in v0.2.7 and Vue 3 in v0.3.0.

To install the latest version, run:

```sh
npm install laravel-mix-svg-vue
```

Or if you prefer yarn:

```sh
yarn add laravel-mix-svg-vue
```

**Comment by dacoto** [comment]
thank you so much, good job!
